version: '3.5'

networks:
  backbone:
    external: true
  local:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ${SRC_DIR:-.}/nginx/httpd.conf:/etc/nginx/conf.d/default.conf:ro
      - ${BASE_DIR:-./var}/static:/static
      - ${BASE_DIR:-./var}/media:/media
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL:  ${LETSENCRYPT_EMAIL:-}
    networks:
      - backbone
      - local
    logging:
      driver: none
    env_file:
      - .env

  frontend:
    #    command: tail -f /dev/null
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/src
      - /src/node_modules

  redis:
    image: redis
    networks:
      - local

  backend:
    build: ${SRC_DIR:-.}/backend
    volumes:
      - ${SRC_DIR:-.}/backend/entrypoint.sh:/entrypoint.sh
      - ${SRC_DIR:-.}/backend:/src
      - ${BASE_DIR:-./var}/static:/static
      - ${BASE_DIR:-./var}/media:/media
      - ${BASE_DIR:-./var}/logs:/logs
      - ${BASE_DIR:-./var}/sessions:/sessions
    env_file:
      - .env
    networks:
      - backbone
      - local
    ports:
      - 8000:8000

  mail:
    image: mailhog/mailhog
    logging:
      driver: none
    networks:
      - local
    ports:
      - 8025:8025
