version: '3.5'

services:

  frontend:
    #    command: tail -f /dev/null
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/src
      - /src/node_modules

  redis:
    image: redis

  backend:
    build: ${SRC_DIR:-.}/backend
    volumes:
      - ${SRC_DIR:-.}/backend/entrypoint.sh:/entrypoint.sh
      - ${SRC_DIR:-.}/backend:/src
      - ${BASE_DIR:-./var}/static:/static
      - ${BASE_DIR:-./var}/media:/media
      - ${BASE_DIR:-./var}/logs:/logs
    env_file:
      - .env
    ports:
      - 8000:8000
