version: '3.5'

services:

  frontend:
    #    command: tail -f /dev/null
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/src
      - /src/node_modules

  redis:
    image: redis

  backend:

    build: ${SRC_DIR:-.}/backend
    volumes:
      - ${SRC_DIR:-.}/backend/entrypoint.sh:/entrypoint.sh
      - ${SRC_DIR:-.}/backend:/src
      - ${BASE_DIR:-./var}/static:/static
      - ${BASE_DIR:-./var}/media:/media
      - ${BASE_DIR:-./var}/logs:/logs
      - ${BASE_DIR:-./var}/sessions:/sessions
      - ${SRC_DIR:-.}/reaper/templates:/reaper/templates
      - /Users/csp/Projects/session-recorder/.environment/lib/python3.7/site-packages/reapy/tools/network/client.py:/usr/local/lib/python3.7/site-packages/reapy/tools/network/client.py
      - /Users/csp/Projects/session-recorder/.environment/lib/python3.7/site-packages/reapy/tools/network/socket.py:/usr/local/lib/python3.7/site-packages/reapy/tools/network/socket.py
    env_file:
      - .env
    ports:
      - 8000:8000
