# Generated by Django 3.1 on 2020-08-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_session_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
