# Generated by Django 3.1 on 2020-08-31 12:39

from django.db import migrations, models
import django.db.models.deletion


# noinspection PyPep8,PyUnresolvedReferences
class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_take_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active_take',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='models.take'),
        ),
    ]
