# Generated by Django 3.1.2 on 2020-10-17 23:17

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_session_active_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='state',
            field=django_fsm.FSMField(default='started', max_length=50),
        ),
        migrations.AddField(
            model_name='take',
            name='take_mix_processed',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='take',
            name='take_mix_source',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
