# Generated by Django 3.1.3 on 2020-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20201018_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='next_take_tempo',
            field=models.IntegerField(default=120),
        ),
    ]
